name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # required for creating releases and pushing badge updates
  actions: write

jobs:
  test:
    name: Run Tests & Generate Coverage Badge
    runs-on: ubuntu-latest

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git fetch --tags

      - name: Bump version and create tag
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"
          new_tag="v$major.$minor.$((patch + 1))"
          git tag "$new_tag"
          git push origin "$new_tag"
          echo "tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          generate_release_notes: true
          body: |
            🚀 **Automated Release**
            - **Coverage:** ${{ needs.test.outputs.coverage }}%
            - **Triggered by:** ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
