name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # required for creating releases and pushing badge updates
  actions: write

jobs:
  test:
    name: Run Tests & Generate Coverage Badge
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}  # Pass coverage as output

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch all refs

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run Tests
        id: coverage
        run: |
          # Run tests and generate the coverage profile
          go test -v ./... -covermode=count -coverprofile=coverage.out

          # Extract the coverage percentage and clean it up (removes the '%' sign)
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')

          # Debug the extracted coverage value
          echo "Coverage: $COVERAGE%"

          # Set coverage as an environment variable for the next job
          echo "coverage=$COVERAGE" >> $GITHUB_ENV
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

          # Fail the build if coverage is below 80%
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80%, failing the build."
            exit 1
          fi

      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v3
        with:
          filename: coverage.out

      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."

      - name: Push Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use your PAT token stored in secrets
          branch: ${{ github.head_ref }}

  release:
    name: Create Release
    needs: test  # Ensure this job runs after 'test' job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch tags

      - name: Fetch All Tags
        run: git fetch --tags

      - name: Determine Latest Tag and Bump Version
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"
          new_tag="v$major.$minor.$((patch + 1))"
          git tag "$new_tag"
          git push origin "$new_tag"
          echo "tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
          body: |
            🚀 **Automated Release**
            - **Coverage:** ${{ env.coverage }}%  # Pass coverage as an environment variable from the 'test' job
            - **Triggered by:** [@${{ github.actor }}](https://github.com/${{ github.actor }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          coverage: ${{ needs.test.outputs.coverage }}  # Pass coverage from the `test` job as an env variable
